---
title: Party monkey
hero_image: images/banner.png
description: Create a 3D model of a monkey in a party hat using Blender
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4.0.1
last_tested: 2025-01-15
steps:
- title: What you will make
- title: Zooming and rotating
- title: The 3D scene
  completion:
  - engaged
- title: Rendering
- title: Selecting and moving
- title: Add a monkey
- title: Add a hat
- title: Change the lighting
  completion:
  - internal
- title: Challenge
  - challenge: true
- title: What can I do now?
