title: Party Monkey
hero_image: images/banner.png
description: Create a 3D model of a monkey in a party hat using blender
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: "animals"
technologies: ""
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Zooming and rotating
