---
title: पार्टी बंदर
hero_image: images/banner.png
description: Blender का उपयोग करके पार्टी टोपी पहनने वाले बंदर का 3D मॉडल बनाएँ।
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art and design
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4.0.1
last_tested: 2017-01-01
steps:
- title: भूमिका
- title: ज़ूम करना और रोटेट करना
- title: 3D दृश्य
  completion:
  - engaged
- title: प्रस्तुत करना
- title: चयन करना और चलाना
- title: एक बंदर जोड़ें
- title: एक टोपी जोड़ें
- title: प्रकाश व्यवस्था बदलें
  completion:
  - internal
- title: 'चुनौती: एक नया दृश्य'
