---
title: パーティーモンキー
hero_image: images/banner.png
description: Blenderを使ってパーティー用の帽子（ぼうし）をかぶったサルの3Dモデルをつくる
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4.0.1
last_tested: 2017-01-01
steps:
- title: はじめに
  completion: engaged
- title: ズームと回転
- title: 3Dシーン
- title: レンダリング
- title: 選択と移動
- title: サルを追加する
- title: 帽子（ぼうし）を追加する
- title: 照明を変更する
  completion: internal
- title: チャレンジ：新しいシーン
