---
title: Party Affe
hero_image: images/banner.png
description: Erstelle mit Blender ein 3D-Modell eines Affen, der einen Partyhut trägt
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4.0.1
last_tested: 2017-01-01
steps:
- title: Einleitung
- title: Zoomen und drehen
- title: Die 3D-Szene
  completion:
  - engaged
- title: Rendern
- title: Auswählen und verschieben
- title: Füge einen Affen hinzu
- title: Füge einen Hut hinzu
- title: Beleuchtung ändern
  completion:
  - internal
- title: 'Herausforderung: Eine neue Szene'
