---
title: Maimuță petrecăreață
hero_image: images/banner.png
description: Creează, folosind Blender, un model 3D al unei maimuțe ce poartă o pălărie
  de petrecere
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4.0.1
last_tested: 2017-01-01
steps:
- title: Introducere
  completion: engaged
- title: De ce vei avea nevoie
- title: Mărirea și rotirea
- title: Scena 3D
- title: Randare
- title: Selectarea și mutarea
- title: Adaugă o maimuță
- title: Adaugă o pălărie
  completion: internal
- title: Schimbă lumina
- title: 'Provocare: o nouă scenă'
