---
title: La fiesta de la mona
hero_image: images/banner.png
description: Crea un modelo 3D de una mona con un sombrero de fiesta usando Blender
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4.0.1
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Acercar y rotar
  - 
    title: La escena 3D
    completion:
      - engaged
  - 
    title: Representación gráfica
  - 
    title: Seleccionar y mover
  - 
    title: Agrega una mona
  - 
    title: Agrega un sombrero
  - 
    title: Cambia la iluminación
    completion:
      - internal
  - 
    title: 'Desafío: una nueva escena'
