---
title: قرد الحفلة
hero_image: images/banner.png
description: قم بإنشاء نموذج ثلاثي الأبعاد لقرد في قبعة الحفلة باستخدام Blender
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4.0.1
last_tested: 2017-01-01
steps:
- title: المقدمة
- title: تكبير وتدوير
- title: المشهد الثلاثي الأبعاد
  completion:
  - engaged
- title: استدعاء
- title: اختيار و نقل
- title: أضف قرد
- title: أضف قبعة
- title: تغيير الإضاءة
  completion:
  - internal