---
title: Singe fêtard
hero_image: images/banner.png
description: Crée un modèle 3D d'un singe avec un chapeau de fête à l'aide de Blender
theme: turquoise #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4.0.1
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Zooming and rotating
  - 
    title: The 3D scene
  - 
    title: Rendering
  - 
    title: Selecting and moving
  - 
    title: Add a monkey
  - 
    title: Add a hat
  - 
    title: Change the lighting
  - 
    title: "Challenge: a new scene"
